# Copyright (c) Abstract Machines
# SPDX-License-Identifier: Apache-2.0

# CoAP is temporarily ignored since we don't have tests for it yet.
coverage:
  ignore:
    - "tools/*"
    - "cmd/*"
    - "coap/*"
    - "*/mocks/*"
    - "*/middleware/*"
    - "pkg/sid/mock.go"
    - "pkg/tracing/utils.go"
    - "pkg/prometheus/*"
